/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login and get access token.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current user information.
         */
        get: operations["get_current_user_info_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description List all alerts with filtering and pagination.
         */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        /**
         * Create Alert
         * @description Create a new alert.
         */
        post: operations["create_alert_api_v1_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alert
         * @description Get alert details.
         */
        get: operations["get_alert_api_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Alert
         * @description Delete an alert. Only DRAFT alerts can be deleted.
         */
        delete: operations["delete_alert_api_v1_alerts__alert_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Alert
         * @description Update an alert. Only DRAFT or SCHEDULED alerts can be updated.
         */
        patch: operations["update_alert_api_v1_alerts__alert_id__patch"];
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Alert
         * @description Send an alert immediately or schedule it.
         */
        post: operations["send_alert_api_v1_alerts__alert_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Alert
         * @description Cancel a scheduled alert.
         */
        post: operations["cancel_alert_api_v1_alerts__alert_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List all templates.
         */
        get: operations["list_templates_api_v1_templates_get"];
        put?: never;
        /**
         * Create Template
         * @description Create a new template (Admin only).
         */
        post: operations["create_template_api_v1_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description Get template by ID.
         */
        get: operations["get_template_api_v1_templates__template_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Template
         * @description Delete a template (Admin only).
         */
        delete: operations["delete_template_api_v1_templates__template_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Template
         * @description Update a template (Admin only).
         */
        patch: operations["update_template_api_v1_templates__template_id__patch"];
        trace?: never;
    };
    "/api/v1/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cells
         * @description List all cell sites.
         */
        get: operations["list_cells_api_v1_cells_get"];
        put?: never;
        /**
         * Create Cell
         * @description Create a new cell site (Admin only).
         */
        post: operations["create_cell_api_v1_cells_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cells/{cell_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cell
         * @description Get cell site by ID.
         */
        get: operations["get_cell_api_v1_cells__cell_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Cell
         * @description Delete a cell site (Admin only).
         */
        delete: operations["delete_cell_api_v1_cells__cell_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Cell
         * @description Update a cell site (Admin only).
         */
        patch: operations["update_cell_api_v1_cells__cell_id__patch"];
        trace?: never;
    };
    "/api/v1/cells/{cell_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cell Status
         * @description Get real-time status of a cell site (queries eNB via SSH).
         */
        get: operations["get_cell_status_api_v1_cells__cell_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cells/health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Health Check All
         * @description Run health check on all active cell sites.
         */
        post: operations["health_check_all_api_v1_cells_health_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Stats
         * @description Get dashboard statistics.
         */
        get: operations["get_dashboard_stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Health check endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Detailed health check.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertCellResponse */
        AlertCellResponse: {
            /** Cell Id */
            cell_id: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Sent At */
            sent_at?: string | null;
            /** Id */
            id: string;
            /** Cell Name */
            cell_name?: string | null;
        };
        /** AlertCreate */
        AlertCreate: {
            alert_type: components["schemas"]["AlertType"];
            /** Message Id */
            message_id: number;
            /** Content */
            content: string;
            /**
             * Duration
             * @default 3600
             */
            duration: number;
            /** Cell Ids */
            cell_ids: string[];
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Template Id */
            template_id?: string | null;
        };
        /** AlertDetailResponse */
        AlertDetailResponse: {
            alert_type: components["schemas"]["AlertType"];
            /** Message Id */
            message_id: number;
            /** Content */
            content: string;
            /**
             * Duration
             * @default 3600
             */
            duration: number;
            /** Id */
            id: string;
            status: components["schemas"]["AlertStatus"];
            /** Scheduled At */
            scheduled_at: string | null;
            /** Sent At */
            sent_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Created By */
            created_by: string;
            /** Template Id */
            template_id: string | null;
            /**
             * Cells
             * @default []
             */
            cells: components["schemas"]["AlertCellResponse"][];
            /**
             * Logs
             * @default []
             */
            logs: components["schemas"]["AlertLogResponse"][];
            created_by_user?: components["schemas"]["UserResponse"] | null;
        };
        /** AlertLogResponse */
        AlertLogResponse: {
            /** Id */
            id: string;
            /** Action */
            action: string;
            /** Status */
            status: string;
            /** Message */
            message: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** AlertResponse */
        AlertResponse: {
            alert_type: components["schemas"]["AlertType"];
            /** Message Id */
            message_id: number;
            /** Content */
            content: string;
            /**
             * Duration
             * @default 3600
             */
            duration: number;
            /** Id */
            id: string;
            status: components["schemas"]["AlertStatus"];
            /** Scheduled At */
            scheduled_at: string | null;
            /** Sent At */
            sent_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Created By */
            created_by: string;
            /** Template Id */
            template_id: string | null;
            /**
             * Cells
             * @default []
             */
            cells: components["schemas"]["AlertCellResponse"][];
        };
        /** AlertSendRequest */
        AlertSendRequest: {
            /**
             * Immediate
             * @default true
             */
            immediate: boolean;
        };
        /** AlertSendResponse */
        AlertSendResponse: {
            /** Id */
            id: string;
            status: components["schemas"]["AlertStatus"];
            /** Message */
            message: string;
            /** Job Id */
            job_id?: string | null;
        };
        /** AlertStats */
        AlertStats: {
            /** Total */
            total: number;
            /** Sent */
            sent: number;
            /** Scheduled */
            scheduled: number;
            /** Failed */
            failed: number;
            /** Draft */
            draft: number;
        };
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "DRAFT" | "SCHEDULED" | "SENDING" | "SENT" | "FAILED" | "CANCELLED";
        /**
         * AlertType
         * @enum {string}
         */
        AlertType: "CMAS" | "ETWS";
        /** AlertUpdate */
        AlertUpdate: {
            /** Content */
            content?: string | null;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Duration */
            duration?: number | null;
            /** Cell Ids */
            cell_ids?: string[] | null;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** CellSiteCreate */
        CellSiteCreate: {
            /** Name */
            name: string;
            /** Cell Id */
            cell_id: string;
            /** Enb Ip */
            enb_ip: string;
            /**
             * Enb Port
             * @default 22
             */
            enb_port: number;
            /**
             * Enb Username
             * @default root
             */
            enb_username: string;
            /**
             * Enb Config Path
             * @default /etc/srsenb/sib.conf
             */
            enb_config_path: string;
            /** Location */
            location?: string | null;
        };
        /** CellSiteResponse */
        CellSiteResponse: {
            /** Name */
            name: string;
            /** Cell Id */
            cell_id: string;
            /** Enb Ip */
            enb_ip: string;
            /**
             * Enb Port
             * @default 22
             */
            enb_port: number;
            /**
             * Enb Username
             * @default root
             */
            enb_username: string;
            /**
             * Enb Config Path
             * @default /etc/srsenb/sib.conf
             */
            enb_config_path: string;
            /** Location */
            location?: string | null;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Last Seen */
            last_seen: string | null;
            /** Last Health Check */
            last_health_check: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CellSiteUpdate */
        CellSiteUpdate: {
            /** Name */
            name?: string | null;
            /** Enb Ip */
            enb_ip?: string | null;
            /** Enb Port */
            enb_port?: number | null;
            /** Enb Username */
            enb_username?: string | null;
            /** Enb Config Path */
            enb_config_path?: string | null;
            /** Location */
            location?: string | null;
            /** Status */
            status?: string | null;
        };
        /** CellStats */
        CellStats: {
            /** Total */
            total: number;
            /** Active */
            active: number;
            /** Offline */
            offline: number;
        };
        /** CellStatusResponse */
        CellStatusResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Enb Status */
            enb_status?: {
                [key: string]: unknown;
            } | null;
            /** Last Health Check */
            last_health_check: string | null;
        };
        /** NetworkStats */
        NetworkStats: {
            /** eNBs Connected */
            enbs_connected: number;
            /** MMEs Connected */
            mmes_connected: number;
            /** Cells Online */
            cells_online: number;
        };
        /** DashboardStats */
        DashboardStats: {
            alerts: components["schemas"]["AlertStats"];
            today: components["schemas"]["TodayStats"];
            cells: components["schemas"]["CellStats"];
            network: components["schemas"]["NetworkStats"];
            /** Success Rate */
            success_rate: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedResponse */
        PaginatedResponse: {
            /** Data */
            data: unknown[];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** TemplateCreate */
        TemplateCreate: {
            /** Name */
            name: string;
            /** Category */
            category: string;
            alert_type: components["schemas"]["AlertType"];
            /** Message Id */
            message_id: number;
            /** Content */
            content: string;
            /**
             * Default Duration
             * @default 3600
             */
            default_duration: number;
        };
        /** TemplateResponse */
        TemplateResponse: {
            /** Name */
            name: string;
            /** Category */
            category: string;
            alert_type: components["schemas"]["AlertType"];
            /** Message Id */
            message_id: number;
            /** Content */
            content: string;
            /**
             * Default Duration
             * @default 3600
             */
            default_duration: number;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TemplateUpdate */
        TemplateUpdate: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Content */
            content?: string | null;
            /** Default Duration */
            default_duration?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** TodayStats */
        TodayStats: {
            /** Sent */
            sent: number;
            /** Scheduled */
            scheduled: number;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** @default OPERATOR */
            role: components["schemas"]["UserRole"];
            /** Password */
            password: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            /** @default OPERATOR */
            role: components["schemas"]["UserRole"];
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "ADMIN" | "OPERATOR" | "VIEWER";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: string | null;
                /** @description Filter by type (CMAS/ETWS) */
                alert_type?: string | null;
                page?: number;
                limit?: number;
                /** @description Sort field */
                sort_by?: string;
                /** @description Sort order (asc/desc) */
                sort_order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_api_v1_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_api_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_api_v1_alerts__alert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_api_v1_alerts__alert_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_alert_api_v1_alerts__alert_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertSendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_alert_api_v1_alerts__alert_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_templates_get: {
        parameters: {
            query?: {
                /** @description Filter by category */
                category?: string | null;
                /** @description Filter by alert type */
                alert_type?: string | null;
                /** @description Only return active templates */
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_v1_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_v1_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cells_api_v1_cells_get: {
        parameters: {
            query?: {
                /** @description Filter by status */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellSiteResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_cell_api_v1_cells_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CellSiteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellSiteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cell_api_v1_cells__cell_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellSiteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_cell_api_v1_cells__cell_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_cell_api_v1_cells__cell_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CellSiteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellSiteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cell_status_api_v1_cells__cell_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_all_api_v1_cells_health_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellStatusResponse"][];
                };
            };
        };
    };
    get_dashboard_stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
